### ISSUE TITLE
Add NAIF ID to Target?

### ISSUE THREAD

**Issue by wlandry** [opencadc/caom2#21]
Most (but not all) moving object targets have a NAIF ID.  Target already has a keywords field, so we can add it there.  It might be better for there to be a separate field for it.  I am not sure, though.

**Comment by pdowler** [comment]
Since there are definitely multiple types of IDs and individual targets may have multiple IDs the conceptual model is definitely Target -> TargetID in a one-to-many relationship. The different types suggest using URIs with scheme == type and scheme-specific-part = ID, for example
`naif:170100`
and then adding a field to Target to store a list of URIs so it is separate from keywords and more syntactically strict.

**Comment by pdowler** [comment]
Having more than one resolvable identifier is more complicated and adds minimal value. 

Target [0..1] targetID
