### ISSUE TITLE
Requiring pixel values for some WCS

### ISSUE THREAD

**Issue by dr-rodriguez** [opencadc/caom2#29]
While validating CAOM v2.3 XML files, I’ve run into an error which appear to be driven by the schema design: in the SpectralWCS, PolarizationWCS, and TemporalWCS (energy, polarization, and
time in Chunk, respectively) there is an _axis_ element that contains a _bounds_ element of type **CoordsBound1D**. This element consists of samples of start/end points defined by **RefCoord** which currently require both _pix_ and _val_ to be provided. While the physical value (_val_) should always be present, it’s not clear that a pixel value (_pix_) will be and that’s been the case for some of the data I’ve been working with.
A simple fix may be to set these as minOccurs="0" in the schema.

**Comment by pdowler** [comment]
I will consult older use case docs and discover why it is done that way...

**Comment by pdowler** [comment]
The goal of the range/bounds/function objects in the wcs part of the model is to allow data providers to provide as little or as much metadata about the data array as was feasible. Normally only one of these is created per axis. The minimum was designed so that standard code could determine the dimensions and a possibly crude bounding box to aggregate into the plane metadata. 

Now that we are moving to never compute plane metadata and provide it independently, the "range" values are no longer useful. The "bounds" objects have two possible uses:

1. if the valid portion of the data array is smaller than the whole array described by the function, the bounds can be used as a footprint-within-the array; cutouts can try to return valid pixels only

2. if the function representation is not feasible (eg multi-order spectroscopic data), the bounds can be used to define "tiles" and cutouts can extract tiles (not exact cutout but better than nothing). CADC uses this for some CFHT spectra, defining ~20-40 tiles for a spectrum with 200k pixels; a narrow cutouts can extract a single tile of 5-10k pixels.

Recommendation: if you have the CoordFunction, leave the other two null unless use #1 above is valuable
