### ISSUE TITLE
Add data release date to Artifacts

### ISSUE THREAD

**Issue by DaftPict** [opencadc/caom2#84]
JWST has file based release dates rather than observation based. Would like to be able to optionally add dataRelease to Artifact - we could then roll up to higher levels as needed.

**Comment by pdowler** [comment]
Different planes in an observation can have different release dates so this is a per-plane issue.

Use cases led to adding releaseType some artifacts to use the Plane.metaRelease instead of Plane.dataRelease but in a very simple declarative fashion... the use cases were mainly to support preview policies but could be used for other kinds of files (eg. detailed metadata outside CAOM).

Q: do different artifacts in a plane have different dataRelease dates but the same releaseType?   That is, do you have release dates other than those two values with those meanings?

**Comment by DaftPict** [comment]
As much as I hate the way this is implemented, JWST has individual data release dates for every file rather than a single release date for an observation or even each plane of an observation so I don’t see anyway around this other than add releaseDate to each artifact since they may all be different.
I don’t see any need for any releaseTypes other than data or meta

**Comment by pdowler** [comment]
analysis: 
* would have to define rules saying something like "release date from plane applies unless overridden by a more specific value in the artifact"... that's basically the same behaviour as the productType that can be specified at one or more of artifact-part-chunk
* the CADC portal predicts that a user will be allowed to download data before offering a checkbox of one-click download link... as long as the Plane.dataRelease was set using an Artifact.dataRelease from the artifact with productType = science this service could act in a sensible way and the "prediction" that data access was permitted would be (usefully) correct.

**Comment by pdowler** [comment]
would also imply/require Artifact.dataReadGroups
added to UML
